- name: Install npm and nodejs
  apt:
    pkg:
    - nodejs
    - npm
  register: output
  tags:
    - npm


- name: npm install npm --global
  npm:
    name: npm
    global: yes
    state: latest
  register: output
  tags:
    - npm
