- name: Update repositories cache
  apt:
    update_cache: yes
  register: output
  tags:
    - observium

- name: Install packages required
  apt:
    pkg:
    - libapache2-mod-php7.2
    - php7.2-cli
    - php7.2-mysql
    - php7.2-mysqli
    - php7.2-gd 
    - php7.2-json
    - php-pear 
    - snmp 
    - snmp-mibs-downloader
    - snmpd
    - fping 
    - mysql-server 
    - mysql-client 
    - python-mysqldb 
    - rrdtool 
    - subversion 
    - whois 
    - mtr-tiny
    - ipmitool 
    - graphviz 
    - imagemagick 
    - apache2
  register: output
  tags:
    - observium

- name: Creating /opt/observium
  shell: |
   mkdir -p /opt/observium
  register: output
  tags:
    - observium

- name: Downloading Observium
  shell: |
   cd /opt
   wget http://www.observium.org/observium-community-latest.tar.gz
   tar zxvf observium-community-latest.tar.gz
  register: output
  tags:
    - observium

- name: Copy config.php.default to config.php
  copy:
     src: /opt/observium/config.php.default
     dest: /opt/observium/config.php
     remote_src: yes
  register: output
  tags:
    - observium

- name: Replace some variables in config.php (1/3)
  lineinfile:
    path: /opt/observium/config.php
    regexp: "$config['db_user']      = 'USERNAME';"
    line: "$config['db_user']      = 'observium';"
  register: output
  tags:
    - netbox

- name: Replace some variables in config.php (2/3)
  lineinfile:
    path: /opt/observium/config.php
    regexp: "$config['db_pass']      = 'PASSWORD';"
    line: "$config['db_pass']      = 'OBS_PASSWORD';"
  register: output
  tags:
    - netbox

- name: Replace some variables in config.php (3/3)
  blockinfile:
    path: /opt/observium/config.php
    insertafter: "// End config.php"
    block: |
      $config['base_url']        = "http://lab.glonk.net:6789/cnajar/observium/";
  register: output
  tags:
    - netbox

  
- name: Configuring MySQL (for Ubuntu 18.04 and MYSQL <8)
  shell: |
   mysql -uroot  -e "CREATE DATABASE observium DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci"
   mysql -uroot  -e "GRANT ALL PRIVILEGES ON observium.* TO 'observium'@'localhost' IDENTIFIED BY 'OBS_PASSWORD'"
   cd /opt/observium
   ./discovery.php -u
  register: output
  tags:
    - observium

- name : Creating required directories (logs, rrd)
  shell: |
   mkdir -p /opt/observium/logs
   mkdir -p /opt/observium/rrd
   chown www-data:www-data /opt/observium/rrd
  register: output
  tags:
    - observium

- name: Configuring Snmpd
  copy:
     src: configs/snmpd.conf
     dest: /etc/snmp/snmpd.conf
  register: output
  tags:
    - observium

- name: Restarting Snmpd
  shell: |
    service snmpd restart
  register: output
  tags:
    - observium

- name: Configuring Apache 2.4
  copy:
     src: configs/apache.cfg
     dest: /etc/apache2/sites-available/000-default.conf
  register: output
  tags:
    - observium

- name: Enable Apache mod_rewrite
  shell: |
    a2enmod rewrite
    apache2ctl restart
  register: output
  tags:
    - observium

- name: Add admin user and add localhost device to observium
  shell: |
    cd /opt/observium
    ./adduser.php admin admin55 10
    ./add_device.php 127.0.0.1 Ex@mPL3 v2c
    ./discovery.php -h all
    ./poller.php -h all
  register: output
  tags:
    - observium

- name: Touching /etc/cron.d/observium
  file:
    path: /etc/cron.d/observium
    state: touch
    mode: '0644'
  register: output
  tags:
    - observium

- name: Add cron for polling
  copy:
     src: configs/observium.cron
     dest: /etc/cron.d/observium
  register: output
  tags:
    - observium

